Basic Tutorial System
kevinsun-dev/core-impact pull request #103
Opened 2021-05-03 23:06 UTC by kevinsun-dev

## Overview

Added a basic tutorial system that teaches:
 - Dragging stardust to the core
 - Avoiding stardust of a different color
 - Locking in
 - Opponent planets
 - Feedback system
 - Power ups
 - Win condition

## Changes Made

 - Removed TutorialMenu
 - Added TutorialScene

## Next Steps

 - Solve crash on line
 - Add Visual UI elements for understanding power-ups
 - More closely align the basic tutorial with the designs

## Screenshots

<img width="1025" alt="Screen Shot 2021-05-03 at 7 04 31 PM" src="https://user-images.githubusercontent.com/12884206/116943976-95719500-ac42-11eb-9dbc-77618a9eaf8e.png">
<img width="1024" alt="Screen Shot 2021-05-03 at 7 05 34 PM" src="https://user-images.githubusercontent.com/12884206/116943979-960a2b80-ac42-11eb-80f9-a0cd7442c12b.png">

2021-05-03 23:15 UTC, henryz2000 requested changes, later dismissed

2021-05-03 23:15 UTC, henryz2000 commented on source/CIGameScene.cpp
> +    }
should set this to be a getter

2021-05-03 23:15 UTC, henryz2000 commented on source/CIPauseMenu.h
> +    bool _exitGame;
should not be public

2021-05-04 00:55 UTC, kevinsun-dev commented on source/CIGameScene.cpp
> +    }
Good feedback, fixed 👍

2021-05-04 00:55 UTC, kevinsun-dev commented on source/CIPauseMenu.h
> +    bool _exitGame;
Yup, moved to protected. 👍

2021-05-04 19:23 UTC, wlong123 approved these changes
LGTM! Just the one minor comment for exiting the game from the pause menu

2021-05-04 19:23 UTC, wlong123 commented on source/CIGameScene.cpp
> +        _winScene->setDisplay(false);
I think you want something along the lines of _pauseMenu->setDisplay(false)

2021-05-04 21:20 UTC, merged